# Generated by Django 3.1.2 on 2021-03-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_name', models.CharField(max_length=250)),
                ('pr_date', models.DateField()),
                ('pr_desc', models.CharField(max_length=500)),
                ('pr_price', models.IntegerField()),
                ('pr_img', models.ImageField(upload_to='shop/image')),
            ],
        ),
    ]
