# Generated by Django 3.1.2 on 2021-04-27 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_categorie_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moreimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images', models.ImageField(upload_to='')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='shop.product')),
            ],
        ),
    ]
