# Generated by Django 3.1.2 on 2021-04-27 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_moreimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreimages',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product'),
        ),
    ]
