# Generated by Django 3.1.2 on 2021-04-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_review_idr'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Model',
            field=models.CharField(default='default', max_length=266),
            preserve_default=False,
        ),
    ]
