# Generated by Django 3.1.2 on 2021-04-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=600)),
                ('Contact', models.CharField(max_length=600)),
                ('Username', models.CharField(max_length=600)),
            ],
        ),
    ]
