# Generated by Django 3.1.2 on 2021-04-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='Product',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
