# Generated by Django 3.1.2 on 2021-04-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_buy_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='Product',
            new_name='Productdet',
        ),
    ]
