# Generated by Django 3.1.2 on 2021-04-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210428_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='color',
            field=models.CharField(default='default', max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buy',
            name='model',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='buy',
            name='size',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
