# Generated by Django 3.0 on 2021-05-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_order_historie'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='img',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
